version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdatavol:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  chrome:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - 4444:4444
  backend: &backend
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
    depends_on:
      - redis
      - db
      - chrome
  # delayed_job:
  #   <<: *backend
  #   command: bundle exec rails jobs:work
  sidekiq:
    <<: *backend
    command: bundle exec sidekiq -C config/sidekiq.yml
    environment:
      REDIS_URL: redis://redis:6379
  web:
    <<: *backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      WEBPACKER_DEV_SERVER_HOST: webpack
    depends_on:
      - webpack
  webpack:
    <<: *backend
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: bash -c "bin/webpack-dev-server"
    ports:
      - 3035:3035
volumes:
  pgdatavol:
  bundle: